# get-installer — static distribution-channel image.
#
# Serves the installer bytes (install.sh, install.ps1, installer.py,
# registry.json) over HTTP. Pure read-side — no database, no auth.
# Suitable for behind a CDN like Cloudflare / Fastly.
#
# Multi-arch: builds for both linux/amd64 and linux/arm64 from the same
# Dockerfile. Build via buildx (see scripts/build-multiarch.sh):
#
#   docker buildx build \
#       --platform linux/amd64,linux/arm64 \
#       --tag simtabi/get-installer:dev \
#       --load .
#
# Base: Ubuntu 26.04 LTS — official Docker Hub image, multi-arch
# manifest list. Falls back to 24.04 if 26.04 isn't on Docker Hub
# yet:
#   docker buildx build --build-arg UBUNTU_TAG=24.04 …
#
# Pin by SHA in production by replacing ``ubuntu:${UBUNTU_TAG}`` with
# ``ubuntu:${UBUNTU_TAG}@sha256:<digest>``.

# `--platform=$BUILDPLATFORM` makes buildx use the native arch for any
# multi-stage build helpers; the final stage targets `$TARGETPLATFORM`
# automatically.
ARG BUILDPLATFORM
ARG TARGETPLATFORM
ARG TARGETARCH
ARG UBUNTU_TAG=26.04
FROM --platform=$TARGETPLATFORM ubuntu:${UBUNTU_TAG}

LABEL org.opencontainers.image.title="get-installer"
LABEL org.opencontainers.image.description="Static distribution channel for the Simtabi installer"
LABEL org.opencontainers.image.source="https://github.com/simtabi/get-installer"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.vendor="Simtabi LLC"

ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Etc/UTC \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8

# Minimal package set: nginx (the web server) + supervisor (the process
# manager) + python3.12 (for any local bundle rebuilds + healthchecks).
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
        ca-certificates \
        nginx \
        python3.12 \
        python3-pip \
        supervisor \
        curl \
        tini \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy the artefacts the CDN serves. Built locally before `docker build`
# via `python scripts/bundle.py`.
COPY dist/installer.py             /srv/www/installer.py
COPY dist/installer.py.sha256      /srv/www/installer.py.sha256
COPY bootstrap/install.sh          /srv/www/install.sh
COPY bootstrap/install.ps1         /srv/www/install.ps1
COPY registry.json                 /srv/www/registry.json
COPY schemas/registry.schema.json  /srv/www/schemas/registry.schema.json

# Per-product convenience aliases. Generated by an entrypoint script
# from registry.json so we don't hand-maintain a per-product dir.
COPY deploy/build-aliases.sh /usr/local/bin/build-aliases.sh
RUN chmod +x /usr/local/bin/build-aliases.sh && /usr/local/bin/build-aliases.sh

COPY deploy/nginx.conf /etc/nginx/nginx.conf
COPY deploy/supervisor-static.conf /etc/supervisor/conf.d/get-installer.conf

# Drop privileges — nginx + supervisor run as the `www-data` user that
# Ubuntu ships pre-created.
USER root
RUN chown -R www-data:www-data /srv/www \
 && chmod -R a+rX /srv/www

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s \
  CMD curl -fsS http://127.0.0.1/install.sh > /dev/null || exit 1

ENTRYPOINT ["tini", "--", "/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
